apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-iam-config
  namespace: agentic-iam
  labels:
    app.kubernetes.io/name: agentic-iam
    app.kubernetes.io/component: config
data:
  # Core Configuration
  AGENTIC_IAM_ENVIRONMENT: "production"
  AGENTIC_IAM_API_HOST: "0.0.0.0"
  AGENTIC_IAM_API_PORT: "8000"
  AGENTIC_IAM_DASHBOARD_HOST: "0.0.0.0"
  AGENTIC_IAM_DASHBOARD_PORT: "8501"
  
  # Database Configuration
  AGENTIC_IAM_DATABASE_URL: "postgresql://agentic_user:$(POSTGRES_PASSWORD)@postgres-service:5432/agentic_iam"
  AGENTIC_IAM_REDIS_URL: "redis://redis-service:6379/0"
  
  # Feature Flags
  AGENTIC_IAM_ENABLE_TRUST_SCORING: "true"
  AGENTIC_IAM_ENABLE_AUDIT_LOGGING: "true"
  AGENTIC_IAM_ENABLE_MFA: "true"
  AGENTIC_IAM_ENABLE_FEDERATED_AUTH: "false"
  AGENTIC_IAM_ENABLE_ANOMALY_DETECTION: "true"
  AGENTIC_IAM_ENABLE_METRICS: "true"
  AGENTIC_IAM_PROMETHEUS_ENABLED: "true"
  
  # Logging Configuration
  AGENTIC_IAM_LOG_LEVEL: "INFO"
  AGENTIC_IAM_LOG_FILE: "/app/logs/agentic_iam.log"
  AGENTIC_IAM_ENABLE_JSON_LOGGING: "true"
  
  # Performance Configuration
  AGENTIC_IAM_RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  AGENTIC_IAM_SESSION_TTL: "3600"
  AGENTIC_IAM_JWT_TOKEN_TTL: "3600"
  AGENTIC_IAM_MAX_SESSIONS_PER_AGENT: "10"
  
  # Security Configuration
  AGENTIC_IAM_REQUIRE_TLS: "true"
  AGENTIC_IAM_ENABLE_AUDIT_INTEGRITY: "true"
  AGENTIC_IAM_ENABLE_CORS: "true"
  
  # Storage Paths
  AGENTIC_IAM_AGENT_REGISTRY_PATH: "/app/data/agents"
  AGENTIC_IAM_CREDENTIAL_STORAGE_PATH: "/app/data/credentials"
  AGENTIC_IAM_AUDIT_STORAGE_PATH: "/app/data/audit"
  
  # Trust Scoring Configuration
  AGENTIC_IAM_TRUST_SCORE_UPDATE_INTERVAL: "3600"
  AGENTIC_IAM_ANOMALY_THRESHOLD: "0.8"
  
  # Compliance Configuration
  AGENTIC_IAM_AUDIT_RETENTION_DAYS: "365"
  
  # CORS Configuration
  AGENTIC_IAM_CORS_ORIGINS: "https://dashboard.agentic-iam.local,https://api.agentic-iam.local"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: agentic-iam
  labels:
    app.kubernetes.io/name: agentic-iam
    app.kubernetes.io/component: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # Logging format
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'rt=$request_time uct="$upstream_connect_time" '
                        'uht="$upstream_header_time" urt="$upstream_response_time"';

        access_log /var/log/nginx/access.log main;

        # Performance optimizations
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 100M;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml;

        # Security headers
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=dashboard:10m rate=5r/s;

        # Upstream servers
        upstream agentic_api {
            server agentic-iam-service:8000 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }

        upstream agentic_dashboard {
            server agentic-iam-service:8501 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }

        # API Server
        server {
            listen 80;
            server_name api.agentic-iam.local;
            return 301 https://$server_name$request_uri;
        }

        server {
            listen 443 ssl http2;
            server_name api.agentic-iam.local;

            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
            ssl_prefer_server_ciphers off;
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 1h;

            location / {
                limit_req zone=api burst=20 nodelay;
                
                proxy_pass http://agentic_api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
                
                proxy_buffering on;
                proxy_buffer_size 128k;
                proxy_buffers 4 256k;
                proxy_busy_buffers_size 256k;
            }

            location /health {
                proxy_pass http://agentic_api;
                access_log off;
            }
        }

        # Dashboard Server
        server {
            listen 80;
            server_name dashboard.agentic-iam.local;
            return 301 https://$server_name$request_uri;
        }

        server {
            listen 443 ssl http2;
            server_name dashboard.agentic-iam.local;

            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
            ssl_prefer_server_ciphers off;
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 1h;

            location / {
                limit_req zone=dashboard burst=10 nodelay;
                
                proxy_pass http://agentic_dashboard;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # WebSocket support for Streamlit
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 300s;  # Longer timeout for dashboard
            }
        }
    }